### ISSUE TITLE
Review Probelm Statement

### ISSUE THREAD

**Issue by NadaElmasry** [NadaElmasry/CAS741-Project#3]
Review Final Project Problem Statement
Link to Problem Statement: [Problem Statement Folder](https://github.com/NadaElmasry/CAS741-Project/tree/main/docs/ProblemStatementAndGoals)

**Comment by smiths** [comment]
Feedback:

- provide a link to the problem statement file, rather than the folder
- the project cannot just be about visualizing the 3d fMRI scans, you also need an analysis of the files.  This means expanding your goal 3 (segment and track the activity of a selected brain region).  
- include links to similar projects

You should flesh out what you mean by your current goal number 3 (the segmentation goal).  What are you segmenting?

Your project has a large scope.  Are there existing tools, like 3DSlicer, that you can use to make your project feasible in this term.

I'll approve the project, but we need to keep an eye on the scope to make sure that it is feasible.

I added a placeholder for you in the Repos.csv file, but you need to create a merge request with the rest of your information.
